# Green light

## Libraries
```{r message=FALSE}

library(dplyr)
library(lubridate)
library(ggplot2)

```

## Load data
```{r}

df <-
  read.csv("../data/raw/11_4070_2019.07.11_00-00_2019.07.12_00-00.csv",
           sep = ";", skip = 1, fileEncoding = "iso-8859-1") %>% 
  mutate(timestamp = ymd_hms(time, tz = "Europe/Berlin")) %>% 
  arrange(timestamp) %>% 
  mutate(duration = as.numeric(lead(timestamp) - timestamp))

```

## Descriptive statistics
```{r}

df %>% pull(status) %>% unique

print("Grün:")
df %>% filter(status == "Grün") %>% pull(duration) %>% summary
print("Rot:")
df %>% filter(status == "Rot") %>% pull(duration) %>% summary
print("Gelb:")
df %>% filter(status == "Gelb") %>% pull(duration) %>% summary
print("Rot/Gelb:")
df %>% filter(status == "Rot/Gelb") %>% pull(duration) %>% summary

df %>% pull(timestamp) %>% summary

```

## Distribution of duration of "Rot"
```{r}

# green
df %>% filter(status == "Grün") %>% pull(duration) %>% table

df %>% 
  filter(status == "Grün") %>%
  select(duration) %>% 
  ggplot(aes(x = duration)) +
  geom_histogram(bins = 80) +
  scale_x_continuous(breaks = seq(5, 80, by = 3)) +
  theme_bw() +
  labs(title = "Distribution of green phase duration")

# red
df %>% filter(status == "Rot") %>% pull(duration) %>% table

df %>% 
  filter(status == "Rot") %>%
  select(duration) %>% 
  ggplot(aes(x = duration)) +
  geom_histogram(bins = 80) +
  scale_x_continuous(breaks = seq(5, 80, by = 3)) +
  theme_bw() +
  labs(title = "Distribution of red phase duration")

```


## Durations over the course of days
```{r}

df %>% 
  filter(status == "Grün") %>%
  mutate(hour = as.factor(hour(timestamp))) %>% 
  select(hour, duration) %>% 
  ggplot(aes(x = hour, y = duration)) + 
  geom_boxplot() +
  scale_y_continuous(breaks = seq(5, 80, by = 5)) +
  theme_bw() +
  labs(title = "Distribution of green phase duration per hour")

df %>% 
  filter(status == "Rot") %>%
  mutate(hour = as.factor(hour(timestamp))) %>% 
  select(hour, duration) %>% 
  ggplot(aes(x = hour, y = duration)) + 
  geom_boxplot() +
  scale_y_continuous(breaks = seq(5, 80, by = 5)) +
  theme_bw() +
  labs(title = "Distribution of red phase duration per hour")

```

## Plot duration, depending on previous durations
```{r}

# green vs. previous green
df %>% 
  filter(status == "Grün") %>%
  select(duration) %>% 
  mutate(duration_lag_green = lag(duration)) %>% 
  ggplot(aes(x = duration_lag_green, y = duration)) +
  geom_point(alpha = 0.1) +
  theme_bw() +
  labs(title = "Green vs. previous green") +
  ylab("duration_current_green")

# red vs. previous red
df %>% 
  filter(status == "Rot") %>%
  select(duration) %>% 
  mutate(duration_lag_red = lag(duration)) %>% 
  ggplot(aes(x = duration_lag_red, y = duration)) +
  geom_point(alpha = 0.1) +
  theme_bw() +
  labs(title = "Red vs. previous red") +
  ylab("duration_current_red")


# green vs. previous red
df %>% 
  filter(status %in% c("Rot", "Grün")) %>%
  select(status, duration) %>% 
  mutate(duration_lag_other = lag(duration)) %>%
  filter(status == "Grün") %>% 
  # plot
  ggplot(aes(x = duration_lag_other, y = duration)) +
  geom_point(alpha = 0.1) +
  theme_bw() +
  labs(title = "Green vs. previous red") +
  ylab("duration_current_green") +
  xlab("duration_previous_red")

# red vs. previous green
df %>% 
  filter(status %in% c("Rot", "Grün")) %>%
  select(status, duration) %>% 
  mutate(duration_lag_other = lag(duration)) %>%
  filter(status == "Rot") %>% 
  # plot
  ggplot(aes(x = duration_lag_other, y = duration)) +
  geom_point(alpha = 0.1) +
  theme_bw() +
  labs(title = "Red vs. previous green") +
  ylab("duration_current_red") +
  xlab("duration_previous_green")

# green vs. previous green (two steps)
df %>% 
  filter(status == "Grün") %>%
  select(duration) %>% 
  mutate(duration_lag_green = lag(duration, 2)) %>% 
  ggplot(aes(x = duration_lag_green, y = duration)) +
  geom_point(alpha = 0.1) +
  theme_bw() +
  labs(title = "Green vs. previous green two steps") +
  ylab("duration_current_green")

```

## Autocorrelation plot
```{r}

df %>% 
  filter(status == "Grün") %>%
  filter(complete.cases(.)) %>% 
  pull(duration) %>%
  acf()

```

